schema {
  query: Query
  mutation: Mutation
}

type Query {
  runtimeAgent(id: String!): RuntimeAgent!
  runtimeAgents: [RuntimeAgent!]!
  serviceInfo(id: String!): ServiceInfo
  serviceInfos: [ServiceInfo!]!
}

type Mutation {
  addServiceInfo(input: ServiceInfoInput!): ServiceInfo!
  deleteServiceInfo(id: String!): ServiceInfo
}

input ServiceInfoInput {
  id: String!
  name: String!
  uniqueName: String!
  type: String!
  version: String!
}

type ServiceInfo {
  id: String!
  name: String!
  uniqueName: String!
  type: String!
  version: String!
}

type RuntimeAgent {
  id: String!
  name: String!
}